services:
  - type: web
    name: sigepol-backend
    env: python
    region: oregon
    plan: standard
    buildCommand: "./build.sh"
    startCommand: "gunicorn sigepol.wsgi:application --bind 0.0.0.0:10000 --workers 1 --timeout 120"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sigepol.settings
      - key: PYTHON_VERSION
        value: 3.13
      - key: NODE_VERSION
        value: 20.11.1
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://sigepol-backend.onrender.com,https://*.onrender.com"
    ipAllowList: []
